#CONDA_BUILD_SYSROOT:
#  - /opt/MacOSX10.9.sdk   # [osx]
channels:
  - defaults
  - conda-forge
  - deepmodeling
  - nvidia
c_compiler:
  - gcc
cxx_copiler:
  - gxx
c_compiler_version:
  - '7.5.0'
cxx_compiler_version:
  - '7.5.0'
