{% set name = "gromacs-dp" %}
{% set version = "2020.2" %}

package:
  name: gromacs-dp
  version: {{ version }}

build:
  number: 0

source:
  git_url: https://gitlab.com/gromacs/gromacs
  git_rev: v2020.2

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - fftw
    - sysroot_linux-64 2.17
    - intel-openmp
    - mpich
    - xdrfile
    - cudatoolkit 10.1
    - cudatoolkit-dev 10.1
    - cudnn
    - deepmd-kit >=2.0.2 *gpu
    - libdeepmd >=2.0.2 *gpu
    - protobuf 3.9.2
  host:
    - fftw
    - intel-openmp
    - mpich
    - xdrfile
    - libhwloc 
    - libblas
    - liblapack
    - cudatoolkit 10.1
    - cudnn
    - protobuf 3.9.2
    - deepmd-kit >=2.0.2 *gpu
    - libdeepmd >=2.0.2 *gpu
  run:
    - cudatoolkit 10.1
    - cudnn
    - deepmd-kit >=2.0.2 *gpu
    - libdeepmd >=2.0.2 *gpu
    - intel-openmp
    - mpich

test:
  commands:
    - dp -h
    - gmx_mpi -version
    - gmx_mpi mdrun -h

about:
  home: http://www.gromacs.org/
  license: GNU Lesser General Public License (LGPL)
  summary: GROMACS is a versatile package to perform molecular dynamics.

extra:
  recipe-maintainers:
    - Ericwang6
